### ISSUE TITLE
Uses Crt; requires additional fpc packages on FreeBSD

### ISSUE THREAD

**Issue by bbrtj** [plicease/FFI-Platypus-Lang-Pascal#18]
`myunit.pas` file contains a couple of symbols, from which only `Add` is tested. It also uses `Crt` unit, which is not in the default install of fpc under FreeBSD. I think I also needed to install `fpc-rtl` and `fpc-rtl-console` to make it work.
Since symbols that actually use stuff from `Crt` are not used, it would be nice to clean that up so that the module installs without manual action. It seems to only be used in `NoArgs` procedure.

**Comment by plicease** [comment]
I'd be happy to review a PR that cleans up the test.  I think I started testing other things in that unit that I never got around to using and I agree there is no reason to include them at this point, esp. if it is breaking  in some environments.

**Comment by plicease** [comment]
Sorry that took me much longer than I intended, but your PR was included in 0.11 which is on its way to CPAN now.
